### ISSUE TITLE
Search Results does not display the page title

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#56]
![image](https://cloud.githubusercontent.com/assets/15111528/10883398/d8a662e0-81c5-11e5-8a76-8ff47777dd98.png)

**Comment by mr-bobz** [comment]
Had to do some hacks, should be working now :-)

**Comment by HerinHentry** [comment]
Issue still happens. Search for TALA results have issues.
![image](https://cloud.githubusercontent.com/assets/15111528/10967095/4601e8ee-840c-11e5-865c-01c4a6898d6a.png)

**Comment by mr-bobz** [comment]
What is the issue now? We don't show page title for any of the pages, only bread crumb.

The title on breadcrumb and browser matches, as like other pages.

**Comment by HerinHentry** [comment]
I think we need a link to the page from the search results that could take us to the right page. The image I have shown does not have the link. The results are not consistent as the pages are displaying link (As they have longer content) & posts not displaying links.
How can we fix this inconsistency?

**Comment by mr-bobz** [comment]
If the original issue is fixed, pls close this defect. 

There is another for the 'inconsistency': #57

**Comment by HerinHentry** [comment]
Hi @mr-bobz : I think I didn't make it clear earlier.
This is not the page title of the Search results page.This is the page link / page title of each results.

Something like (page link / excerpt of content)

User Experience issue: When the user uses element list to navigate only 3 results are shown in the element list. But the page has 4 results. Which means, the **information displayed for a sighted user is more than the information received for a non-sighted user**. If this issue can be fixed by #57, we can close this off. Please advise.

![image](https://cloud.githubusercontent.com/assets/15111528/11015157/01827c6e-85a7-11e5-9527-5708406a3a4f.png)

![image](https://cloud.githubusercontent.com/assets/15111528/11015132/169beff0-85a6-11e5-96c8-b16b39d16634.png)

**Comment by mr-bobz** [comment]
If the user is looking for "links" only, yes he wont see all if the whole content is present and there is no link for more details. Then it is the same issue as #57. 

This is the WP search behavior. We will have to either investigate using a plugin or making a custom search results page. I don't think either is worth spending time on now, unless someone is free to do so.

**Comment by HerinHentry** [comment]
Agree. Let's close this then.

Sent from my phone

<div>-------- Original message --------</div><div>From: Bobby Joseph notifications@github.com </div><div>Date:08/11/2015  4:40 AM  (GMT+10:00) </div><div>To: mr-bobz/talarts talarts@noreply.github.com </div><div>Cc: HerinHentry herinnisha@gmail.com </div><div>Subject: Re: [talarts] Search Results does not display the page title (#56) </div><div>
</div>If the user is looking for "links" only, yes he wont see all if the whole content is present and there is no link for more details. Then it is the same issue as #57.

This is the WP search behavior. We will have to either investigate using a plugin or making a custom search results page. I don't think either is worth spending time on now, unless someone is free to do so.

**Comment by HerinHentry** [comment]
Agree. This issue can be closed.
